force-app/main/default/objects/SQX_Bulk_Job_Manager__c/SQX_Bulk_Job_Manager__c.object-meta.xml
<CustomObject>
    <label>Bulk Job Manager</label>
    <nameField>
        <displayFormat>Job-{000}-{YYYY}{MM}{DD}</displayFormat>
        <label>Bulk Job Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Jobs Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Bulk_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>SQX_Bulk_Job_Id__c</fullName>
    <label>Bulk Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Bulk_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>SQX_Bulk_Job_Status__c</fullName>
    <label>Bulk Job Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Closed__c.field-meta.xml
<CustomField>
    <fullName>SQX_Closed__c</fullName>
    <formula>SQX_Bulk_Job_Status__c == &apos;JobComplete&apos;</formula>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>SQX_Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Records_Failed__c.field-meta.xml
<CustomField>
    <fullName>SQX_Records_Failed__c</fullName>
    <label># Records Failed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Records_Processed__c.field-meta.xml
<CustomField>
    <fullName>SQX_Records_Processed__c</fullName>
    <label># Records Processed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Records_Success__c.field-meta.xml
<CustomField>
    <fullName>SQX_Records_Success__c</fullName>
    <label># Records Success</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SQX_BulkJobManagerStatusSync.cls
/********************************************************************************************************************
 * Create By  : Pooja P Bhat
 * Description: Batch class to sync the Bulk Manager Job record status, once the BULK API job is completed.
 * CHANGE LOG
 * Date         Story#      ModifiedBy      Reason
 * 23-5-2023                Pooja P Bhat    Created.
 *******************************************************************************************************************/
public class SQX_BulkJobManagerStatusSync implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    public Set<String> failedJobIds = new Set<String>();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String  query   =   'SELECT Id, Name, SQX_Closed__c, SQX_Bulk_Job_Id__c, SQX_Bulk_Job_Status__c,' +
                            'SQX_Records_Failed__c, SQX_Records_Processed__c, SQX_Records_Success__c, SQX_Error_Message__c' +
                            ' FROM SQX_Bulk_Job_Manager__c WHERE SQX_Closed__c = false';
        // System.debug('Query***'+query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, list<SQX_Bulk_Job_Manager__c> listBJM) {
        // System.debug('listBJM before='+listBJM);
        //if(listBJM!=null && !listBJM.isEmpty() && listBJM.size()==1) {
            //SQX_Bulk_Job_Manager__c oBJM = listBJM[0];
        for(SQX_Bulk_Job_Manager__c oBJM: listBJM) {
            Http oHttpJobInfo = new Http();
            HttpRequest jobInfoReq = new HttpRequest();
            jobInfoReq.setMethod('GET');
            jobInfoReq.setEndpoint(URl.getOrgDomainUrl().toExternalForm()+'/services/data/v56.0/jobs/ingest/'+oBJM.SQX_Bulk_Job_Id__c);
            jobInfoReq.setHeader('content-type', 'application/json' );
            jobInfoReq.setHeader('Authorization' ,'Bearer '+userInfo.getSessionId());
            HttpResponse jobInfoResp = oHttpJobInfo.send(jobInfoReq);
            if(jobInfoResp.getStatusCode() <= 299 && jobInfoResp.getBody() != null) {
                // System.debug('jobInfoResp body***'+jobInfoResp.getBody());
                Map<String, Object> jobInfoRespMap = (Map<String, Object>) JSON.deserializeUntyped(jobInfoResp.getBody());
                Integer totalRecords=   Integer.valueOf(jobInfoRespMap.containsKey('numberRecordsProcessed') ? jobInfoRespMap.get('numberRecordsProcessed') : 0);
                Integer recordFailed=   Integer.valueOf(jobInfoRespMap.containsKey('numberRecordsFailed') ? jobInfoRespMap.get('numberRecordsFailed') : 0);
                Integer recrdSuccess=   totalRecords - recordFailed;
                String state        =   String.valueOf(jobInfoRespMap.containsKey('state') ? jobInfoRespMap.get('state') : '');
                String errMsg       =   String.valueOf(jobInfoRespMap.containsKey('errorMessage') ? jobInfoRespMap.get('errorMessage') : '');
                oBJM.SQX_Bulk_Job_Status__c     =   state;
                oBJM.SQX_Records_Processed__c   =   totalRecords;
                oBJM.SQX_Records_Success__c     =   recrdSuccess;
                oBJM.SQX_Records_Failed__c      =   recordFailed;
                oBJM.SQX_Error_Message__c       =   errMsg;
                // System.debug('oBJM='+oBJM);
                //update oBJM;
                // System.debug('recordFailedCount='+recordFailed);
                if(recordFailed > 0) {
                    failedJobIds.add(oBJM.SQX_Bulk_Job_Id__c);
                }
            }
        }  
        // System.debug('listBJM='+listBJM);
        if(!listBJM.isEmpty()) update listBJM;
    }

    public void finish(Database.BatchableContext BC) {
        // System.debug('inside finish status sync batch'+failedJobIds.size() + failedJobIds);
        if(!failedJobIds.isEmpty() && !Test.isRunningTest()) {
            Database.executeBatch(new SQX_BatchCreateCSVFailedImport(failedJobIds),50);
        }
    } 
} //End of SQX_BulkJobManagerStatusSync