force-app/main/default/objects/SQX_Bulk_Job_Manager__c/SQX_Bulk_Job_Manager__c.object-meta.xml
<CustomObject>
    <label>Bulk Job Manager</label>
    <nameField>
        <displayFormat>Job-{000}-{YYYY}{MM}{DD}</displayFormat>
        <label>Bulk Job Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Jobs Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Bulk_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>SQX_Bulk_Job_Id__c</fullName>
    <label>Bulk Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Bulk_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>SQX_Bulk_Job_Status__c</fullName>
    <label>Bulk Job Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Closed__c.field-meta.xml
<CustomField>
    <fullName>SQX_Closed__c</fullName>
    <formula>SQX_Bulk_Job_Status__c == &apos;JobComplete&apos;</formula>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>SQX_Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Records_Failed__c.field-meta.xml
<CustomField>
    <fullName>SQX_Records_Failed__c</fullName>
    <label># Records Failed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Records_Processed__c.field-meta.xml
<CustomField>
    <fullName>SQX_Records_Processed__c</fullName>
    <label># Records Processed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SQX_Bulk_Job_Manager__c/fields/SQX_Records_Success__c.field-meta.xml
<CustomField>
    <fullName>SQX_Records_Success__c</fullName>
    <label># Records Success</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SQX_BulkJobManagerStatusSyncTest.cls
/********************************************************************************************************************
 * Create By  : Pooja P Bhat
 * Description: Test class to cover code coverage and verify logic of class SQX_BulkJobManagerStatusSync
 * CHANGE LOG
 * Date         Story#      ModifiedBy      Reason
 * 24-5-2023                Pooja P Bhat    Created.
 *******************************************************************************************************************/
@isTest
public class SQX_BulkJobManagerStatusSyncTest {
	
    @TestSetup
    static void makeData(){
        List<SQX_Bulk_Job_Manager__c> insertBjmLst = new List<SQX_Bulk_Job_Manager__c>();
        SQX_Bulk_Job_Manager__c oBJM1 = new SQX_Bulk_Job_Manager__c(SQX_Bulk_Job_Id__c='750B0000009aLc5',SQX_Bulk_Job_Status__c='Initializing',SQX_Records_Processed__c=0,SQX_Records_Success__c=0,SQX_Records_Failed__c=0);
        insertBjmLst.add(oBJM1);
        SQX_Bulk_Job_Manager__c oBJM2 = new SQX_Bulk_Job_Manager__c(SQX_Bulk_Job_Id__c='750B0000009aLc6',SQX_Bulk_Job_Status__c='Initializing',SQX_Records_Processed__c=0,SQX_Records_Success__c=0,SQX_Records_Failed__c=0);
        insertBjmLst.add(oBJM2);
        SQX_Bulk_Job_Manager__c oBJM3 = new SQX_Bulk_Job_Manager__c(SQX_Bulk_Job_Id__c='750B0000009aLc7',SQX_Bulk_Job_Status__c='Initializing',SQX_Records_Processed__c=0,SQX_Records_Success__c=0,SQX_Records_Failed__c=0);
        insertBjmLst.add(oBJM3);
        SQX_Bulk_Job_Manager__c oBJM4 = new SQX_Bulk_Job_Manager__c(SQX_Bulk_Job_Id__c='750B0000009aLc8',SQX_Bulk_Job_Status__c='Initializing',SQX_Records_Processed__c=0,SQX_Records_Success__c=0,SQX_Records_Failed__c=0);
        insertBjmLst.add(oBJM4);
        SQX_Bulk_Job_Manager__c oBJM5 = new SQX_Bulk_Job_Manager__c(SQX_Bulk_Job_Id__c='750B0000009aLc9',SQX_Bulk_Job_Status__c='Initializing',SQX_Records_Processed__c=0,SQX_Records_Success__c=0,SQX_Records_Failed__c=0);
        insertBjmLst.add(oBJM5);
        insert insertBjmLst;
    }
    
    @isTest
    static void testBatchJobBJMStatusSync() {
        Test.setMock(HttpCalloutMock.class, new SQX_BulkAPI2UtilityMock());
        Test.startTest();
        Database.executeBatch(new SQX_BulkJobManagerStatusSync());
        Test.stopTest();
        List<SQX_Bulk_Job_Manager__c> bjmLst =  [SELECT Id, Name, SQX_Closed__c, SQX_Bulk_Job_Id__c, 
            SQX_Bulk_Job_Status__c, SQX_Records_Failed__c, SQX_Records_Processed__c, SQX_Records_Success__c, SQX_Error_Message__c
            FROM SQX_Bulk_Job_Manager__c];
        Assert.areEqual(5, bjmLst.size());
        for(SQX_Bulk_Job_Manager__c oBJM : bjmLst) {
            if(oBJM.SQX_Bulk_Job_Id__c=='750B0000009aLc5'){
                Assert.areEqual('Failed',oBJM.SQX_Bulk_Job_Status__c);
                Assert.areEqual(0, oBJM.SQX_Records_Processed__c);
                Assert.areEqual(0, oBJM.SQX_Records_Success__c);
                Assert.areEqual(0, oBJM.SQX_Records_Failed__c);
                Assert.areEqual('InvalidBatch:InvalidBatch:Field name not found:Name',oBJM.SQX_Error_Message__c);
            } else if(oBJM.SQX_Bulk_Job_Id__c=='750B0000009aLc6'){
                Assert.areEqual('Failed',oBJM.SQX_Bulk_Job_Status__c);
                Assert.areEqual(0, oBJM.SQX_Records_Processed__c);
                Assert.areEqual(0, oBJM.SQX_Records_Success__c);
                Assert.areEqual(0, oBJM.SQX_Records_Failed__c);
                Assert.areEqual('InvalidBatch:InvalidBatch:Field name not found:SQX_Part_Number__c',oBJM.SQX_Error_Message__c);
            } else if(oBJM.SQX_Bulk_Job_Id__c=='750B0000009aLc7'){
                Assert.areEqual('JobComplete',oBJM.SQX_Bulk_Job_Status__c);
                Assert.areEqual(100, oBJM.SQX_Records_Processed__c);
                Assert.areEqual(99, oBJM.SQX_Records_Success__c);
                Assert.areEqual(1, oBJM.SQX_Records_Failed__c);
                Assert.isNull(oBJM.SQX_Error_Message__c);
            } else if(oBJM.SQX_Bulk_Job_Id__c=='750B0000009aLc8'){
                Assert.areEqual('JobComplete',oBJM.SQX_Bulk_Job_Status__c);
                Assert.areEqual(200, oBJM.SQX_Records_Processed__c);
                Assert.areEqual(198, oBJM.SQX_Records_Success__c);
                Assert.areEqual(2, oBJM.SQX_Records_Failed__c);
                Assert.isNull(oBJM.SQX_Error_Message__c);
            } else if(oBJM.SQX_Bulk_Job_Id__c=='750B0000009aLc9'){
                Assert.areEqual('JobComplete',oBJM.SQX_Bulk_Job_Status__c);
                Assert.areEqual(150, oBJM.SQX_Records_Processed__c);
                Assert.areEqual(150, oBJM.SQX_Records_Success__c);
                Assert.areEqual(0, oBJM.SQX_Records_Failed__c);
                Assert.isNull(oBJM.SQX_Error_Message__c);
            }
        }             
    }
}